import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

const API_URL = 'http://localhost:8000/api';

export default function Home() {
  const [name, setName] = useState('');
  const [role, setRole] = useState('');
  const [customRole, setCustomRole] = useState('');
  const [useCustom, setUseCustom] = useState(false);
  const [predefinedRoles, setPredefinedRoles] = useState([]);
  const [hoveredFeature, setHoveredFeature] = useState(null);
  const navigate = useNavigate();

  const user = JSON.parse(localStorage.getItem('user') || '{}');

  useEffect(() => {
    if (!user.id) navigate('/login');
    axios.get(`${API_URL}/universal/roles`)
      .then(res => setPredefinedRoles(res.data.predefined_roles));
  }, []);

  const handleStart = () => {
    const finalRole = useCustom ? customRole : role;
    if (!finalRole) return alert('Please select or enter a role');
    localStorage.setItem('selected_role', finalRole);
    localStorage.setItem('employee_name', user.name);
    navigate('/loading-skills');
  };

  const features = [
    { icon: '🧠', title: 'Works for ANY role', desc: 'Marketing, Finance, Tech, Design — any field', color: '#667eea' },
    { icon: '🤖', title: 'AI adaptive test', desc: 'Questions generated by AI in real time', color: '#a78bfa' },
    { icon: '📊', title: 'Deep gap analysis', desc: 'Pinpoint exact skill gaps with explanations', color: '#34d399' },
    { icon: '🎯', title: 'Smart learning path', desc: 'Real YouTube courses mapped to your gaps', color: '#f59e0b' },
  ];

  return (
    <div style={s.page}>
      <div style={s.orb1}/><div style={s.orb2}/><div style={s.orb3}/>

      <nav style={s.nav}>
        <div style={s.navInner}>
          <div style={s.logo}>
            <div style={s.logoMark}><span style={s.logoLetters}>SG</span></div>
            <span style={s.logoText}>SkillGap<span style={{color:'#667eea'}}>.</span></span>
          </div>
          <div style={s.navRight}>
            <span style={{fontSize:'13px', color:'rgba(255,255,255,0.5)'}}>Hi, {user.name}</span>
            {user.is_hr && (
              <button style={s.navBtn} onClick={() => navigate('/hr')}>HR Dashboard</button>
            )}
            <button style={{...s.navBtn, color:'#f87171', borderColor:'rgba(248,113,113,0.3)'}}
              onClick={() => { localStorage.clear(); navigate('/login'); }}>
              Logout
            </button>
          </div>
        </div>
      </nav>

      <div style={s.hero}>
        <div style={s.badge} className="fadeUp">
          <span style={s.badgeDot}/>
          Works for ANY job role — any industry
        </div>

        <h1 style={s.heroTitle} className="fadeUp-1">
          Know Your Gaps.<br/>
          <span style={s.gradient}>Accelerate Growth.</span>
        </h1>

        <p style={s.heroSub} className="fadeUp-2">
          Whether you are a Marketing Manager, CA, Doctor or Engineer —
          our AI builds a personalized skill assessment just for you.
        </p>

        <div style={s.formCard} className="fadeUp-3">
          <div style={s.formHeader}>
            <h2 style={s.formTitle}>Start Your Assessment</h2>
            <span style={s.formBadge}>AI Powered</span>
          </div>

          <div style={s.roleToggle}>
            <button
              style={{...s.toggleBtn, background: !useCustom ? 'rgba(102,126,234,0.2)' : 'transparent', borderColor: !useCustom ? '#667eea' : 'rgba(255,255,255,0.1)', color: !useCustom ? '#a5b4fc' : 'rgba(255,255,255,0.4)'}}
              onClick={() => setUseCustom(false)}
            >Pick from list</button>
            <button
              style={{...s.toggleBtn, background: useCustom ? 'rgba(102,126,234,0.2)' : 'transparent', borderColor: useCustom ? '#667eea' : 'rgba(255,255,255,0.1)', color: useCustom ? '#a5b4fc' : 'rgba(255,255,255,0.4)'}}
              onClick={() => setUseCustom(true)}
            >Type custom role</button>
          </div>

          {!useCustom ? (
            <div style={s.fieldWrap}>
              <label style={s.label}>Select Your Role</label>
              <select
                style={s.input}
                value={role}
                onChange={e => setRole(e.target.value)}
                onFocus={e => { e.target.style.borderColor='#667eea'; e.target.style.boxShadow='0 0 0 3px rgba(102,126,234,0.15)'; }}
                onBlur={e => { e.target.style.borderColor='rgba(255,255,255,0.1)'; e.target.style.boxShadow='none'; }}
              >
                <option value="">Choose from 20+ roles...</option>
                {predefinedRoles.map(r => <option key={r} value={r}>{r}</option>)}
              </select>
            </div>
          ) : (
            <div style={s.fieldWrap}>
              <label style={s.label}>Type Your Role</label>
              <input
                style={s.input}
                placeholder="e.g. Marketing Manager, CA, Doctor..."
                value={customRole}
                onChange={e => setCustomRole(e.target.value)}
                onFocus={e => { e.target.style.borderColor='#667eea'; e.target.style.boxShadow='0 0 0 3px rgba(102,126,234,0.15)'; }}
                onBlur={e => { e.target.style.borderColor='rgba(255,255,255,0.1)'; e.target.style.boxShadow='none'; }}
              />
              <p style={{fontSize:'11px', color:'rgba(255,255,255,0.3)', marginTop:'6px'}}>
                AI will automatically detect required skills for this role
              </p>
            </div>
          )}

          <button
            style={s.primaryBtn}
            onClick={handleStart}
            onMouseOver={e => { e.target.style.transform='translateY(-2px)'; e.target.style.boxShadow='0 8px 30px rgba(102,126,234,0.5)'; }}
            onMouseOut={e => { e.target.style.transform='translateY(0)'; e.target.style.boxShadow='0 4px 20px rgba(102,126,234,0.3)'; }}
          >
            Begin Assessment →
          </button>

          <div style={s.aiNote}>
            <span style={s.aiNoteDot}/>
            <span style={{fontSize:'12px', color:'rgba(255,255,255,0.35)'}}>
              AI builds your skill map automatically — no manual setup needed
            </span>
          </div>
        </div>
      </div>

      <div style={s.features} className="fadeUp-4">
        <p style={s.featuresLabel}>WHAT YOU GET</p>
        <div style={s.featGrid}>
          {features.map((f, i) => (
            <div
              key={i}
              style={{
                ...s.featCard,
                borderColor: hoveredFeature===i ? f.color+'40' : 'rgba(255,255,255,0.06)',
                background: hoveredFeature===i ? `${f.color}08` : 'rgba(255,255,255,0.03)',
                transform: hoveredFeature===i ? 'translateY(-4px)' : 'translateY(0)',
              }}
              onMouseOver={() => setHoveredFeature(i)}
              onMouseOut={() => setHoveredFeature(null)}
            >
              <div style={{...s.featIcon, background:`${f.color}20`}}>
                <span style={{fontSize:'20px'}}>{f.icon}</span>
              </div>
              <div style={{...s.featTitle, color: hoveredFeature===i ? f.color : 'white'}}>{f.title}</div>
              <div style={s.featDesc}>{f.desc}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

const s = {
  page: { minHeight:'100vh', background:'#080818', position:'relative', overflow:'hidden', fontFamily:'Inter, sans-serif' },
  orb1: { position:'absolute', width:'600px', height:'600px', borderRadius:'50%', background:'radial-gradient(circle, rgba(102,126,234,0.15) 0%, transparent 70%)', top:'-200px', left:'-200px', pointerEvents:'none' },
  orb2: { position:'absolute', width:'500px', height:'500px', borderRadius:'50%', background:'radial-gradient(circle, rgba(167,139,250,0.1) 0%, transparent 70%)', top:'200px', right:'-150px', pointerEvents:'none' },
  orb3: { position:'absolute', width:'400px', height:'400px', borderRadius:'50%', background:'radial-gradient(circle, rgba(52,211,153,0.08) 0%, transparent 70%)', bottom:'-100px', left:'30%', pointerEvents:'none' },
  nav: { position:'relative', zIndex:10, borderBottom:'1px solid rgba(255,255,255,0.06)', backdropFilter:'blur(20px)', background:'rgba(8,8,24,0.8)' },
  navInner: { maxWidth:'1100px', margin:'0 auto', padding:'0 32px', height:'64px', display:'flex', alignItems:'center', justifyContent:'space-between' },
  logo: { display:'flex', alignItems:'center', gap:'10px' },
  logoMark: { width:'36px', height:'36px', borderRadius:'10px', background:'rgba(102,126,234,0.15)', border:'1px solid rgba(102,126,234,0.3)', display:'flex', alignItems:'center', justifyContent:'center' },
  logoLetters: { fontSize:'13px', fontWeight:'800', background:'linear-gradient(135deg,#667eea,#a78bfa)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' },
  logoText: { fontSize:'20px', fontWeight:'700', color:'white', letterSpacing:'-0.5px' },
  navRight: { display:'flex', alignItems:'center', gap:'16px' },
  navBtn: { padding:'7px 16px', background:'transparent', border:'1px solid rgba(255,255,255,0.12)', color:'rgba(255,255,255,0.6)', borderRadius:'20px', fontSize:'13px', cursor:'pointer', fontFamily:'Inter, sans-serif', transition:'all 0.2s' },
  hero: { position:'relative', zIndex:1, maxWidth:'600px', margin:'0 auto', padding:'80px 24px 40px', textAlign:'center' },
  badge: { display:'inline-flex', alignItems:'center', gap:'8px', background:'rgba(102,126,234,0.1)', border:'1px solid rgba(102,126,234,0.25)', color:'#a5b4fc', padding:'6px 16px', borderRadius:'20px', fontSize:'12px', fontWeight:'500', marginBottom:'28px' },
  badgeDot: { width:'6px', height:'6px', borderRadius:'50%', background:'#667eea', display:'inline-block' },
  heroTitle: { fontSize:'48px', fontWeight:'800', color:'white', lineHeight:'1.15', marginBottom:'20px', letterSpacing:'-1.5px' },
  gradient: { background:'linear-gradient(135deg, #667eea, #a78bfa, #34d399)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' },
  heroSub: { fontSize:'16px', color:'rgba(255,255,255,0.5)', lineHeight:'1.7', marginBottom:'40px' },
  formCard: { background:'rgba(255,255,255,0.03)', backdropFilter:'blur(20px)', border:'1px solid rgba(255,255,255,0.08)', borderRadius:'24px', padding:'32px', marginBottom:'24px', textAlign:'left' },
  formHeader: { display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:'20px' },
  formTitle: { fontSize:'18px', fontWeight:'600', color:'white' },
  formBadge: { background:'rgba(52,211,153,0.1)', border:'1px solid rgba(52,211,153,0.2)', color:'#34d399', padding:'3px 10px', borderRadius:'12px', fontSize:'12px', fontWeight:'500' },
  roleToggle: { display:'flex', gap:'8px', marginBottom:'16px' },
  toggleBtn: { flex:1, padding:'8px 12px', border:'1px solid', borderRadius:'10px', fontSize:'13px', cursor:'pointer', fontFamily:'Inter, sans-serif', transition:'all 0.2s', fontWeight:'500' },
  fieldWrap: { marginBottom:'16px' },
  label: { display:'block', fontSize:'12px', fontWeight:'500', color:'rgba(255,255,255,0.5)', marginBottom:'8px', letterSpacing:'0.05em', textTransform:'uppercase' },
  input: { width:'100%', padding:'12px 16px', background:'rgba(255,255,255,0.05)', border:'1px solid rgba(255,255,255,0.1)', borderRadius:'12px', color:'white', fontSize:'14px', transition:'all 0.2s', fontFamily:'Inter, sans-serif', outline:'none', boxSizing:'border-box' },
  primaryBtn: { width:'100%', padding:'14px', background:'linear-gradient(135deg, #667eea, #764ba2)', color:'white', border:'none', borderRadius:'14px', fontSize:'15px', fontWeight:'600', cursor:'pointer', marginBottom:'16px', transition:'all 0.2s', boxShadow:'0 4px 20px rgba(102,126,234,0.3)', fontFamily:'Inter, sans-serif' },
  aiNote: { display:'flex', alignItems:'center', gap:'8px' },
  aiNoteDot: { width:'6px', height:'6px', borderRadius:'50%', background:'#667eea', flexShrink:0 },
  features: { position:'relative', zIndex:1, maxWidth:'900px', margin:'0 auto', padding:'0 24px 80px', textAlign:'center' },
  featuresLabel: { fontSize:'11px', fontWeight:'600', color:'rgba(255,255,255,0.3)', letterSpacing:'0.15em', marginBottom:'24px' },
  featGrid: { display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:'16px' },
  featCard: { padding:'24px 20px', borderRadius:'16px', border:'1px solid', transition:'all 0.3s', textAlign:'left' },
  featIcon: { width:'44px', height:'44px', borderRadius:'12px', display:'flex', alignItems:'center', justifyContent:'center', marginBottom:'14px' },
  featTitle: { fontSize:'14px', fontWeight:'600', marginBottom:'6px', transition:'color 0.3s' },
  featDesc: { fontSize:'12px', color:'rgba(255,255,255,0.4)', lineHeight:'1.6' },
};
